name: Build and Package Mod
on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_upload_url: ${{ steps.semantic.outputs.new_release_upload_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semantic Release
        id: semantic
        uses: https://github.com/go-semantic-release/action@v1
        with:
          gitea-token: ${{ secrets.GITHUB_TOKEN }}
          provider: gitea
          gitea-base-url: http://192.168.10.15:30008/
          allow-initial-development-versions: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  package:
    needs: release
    if: needs.release.outputs.new_release_published == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release Zip
        run: |
          mkdir -p build
          zip -r build/DAGMod-${{ needs.release.outputs.new_release_version }}.zip . -x ".gitea/*" ".git/*"

      - name: Upload to Release
        uses: https://github.com/actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.new_release_upload_url }}
          asset_path: build/DAGMod-${{ needs.release.outputs.new_release_version }}.zip
          asset_name: DAGMod-${{ needs.release.outputs.new_release_version }}.zip
          asset_content_type: application/zip